spring.application.name=ChatAssistant
server.port = 8081
spring.ai.mistralai.api-key=rRKP17FguN12WPPU8G1hJ4mwlBwClNQh
spring.ai.mistralai.chat.options.model=mistral-small-2603
spring.data.mongodb.uri=mongodb+srv://sahithakula:saga1208@cluster0.vufslt7.mongodb.net/ChatAssistant?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=ChatAssistant
